main:
  - name: Programa
    url: /syllabus/
    weight: 1
  - name: Planificación
    url: /schedule/
    weight: 2
  - name: Lecturas
    url: /reading/
    weight: 3
  - name: Sesiones
    url: /class/
    weight: 4
  - name: Referencias
    url: /reference/
    weight: 5
  - name: RStudio.cloud
    url: https://rstudio.cloud/
    weight: 6
