main:
  - name: Programa
    url: /programa/
    weight: 1
  - name: Planificación
    url: /schedule/
    weight: 2
  - name: Material
    url: /class/
    weight: 3
  - name: Referencias
    url: /reference/
    weight: 4
  - name: RStudio.cloud
    url: https://rstudio.cloud/
    weight: 5
