baseURL: "https://socviz880.co/"
languageCode: en-us
title: Data Visualization
theme: "kjh-tufte-hugo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Kieran Healy
  thumbnail: /images/dataviz_meta.png
  instructor: 
    name: Kieran Healy
    email: kjhealy@soc.duke.edu
    url: "https://www.kieranhealy.org"
    twitter: kjhealy
    github: kjhealy
    office: "Soc/Psych 255"
  course:
    number: SOCIOL 880
    semester: Spring 2019
    days: "Thursdays"
    time: "10:00am-12:30pm"
    location: "Soc/Psych 248"
    twitter: kjhealy
    dates: "February 28th-April 11th, 2019 "
    github: "kjhealy/socviz880.co"
    copyrightYear: "2019"
    contactDetails: >-
      Office hours: By appointment.
  university: 
    name: Duke University
    url: "https://www.duke.edu"
  school:
    name: Sociology Department
    url: "https://sociology.duke.edu"
  description: "Data Visualization with R"
  primaryColor: "#DA5B69"
  secondaryColor: "#F9983E"
  credits: >-
  logo:
    url: /images/dataviz_hires.png
    alt: Data Visualization
  meta:
    twitterSite: "@kjhealy"
    twitterCreator: "@kjhealy"
